pub mod attack;
pub mod cpu;
pub mod gpu;
pub mod gui;
pub mod rar;
pub mod session;

// Embed PTX strings at compile time (generated by build.rs via nvcc)
pub static RAR5_PTX:  &str = include_str!(concat!(env!("OUT_DIR"), "/rar5_kdf.ptx"));
pub static RAR3_PTX:  &str = include_str!(concat!(env!("OUT_DIR"), "/rar3_kdf.ptx"));
pub static RAR15_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/rar15_filter.ptx"));
